### PR TITLE
Enhancement/module renderer refactor

### PR DESCRIPTION
**Pull request by ch2ch3**
yo @daaain @arnau @davidey 

`ModuleRenderer` -> `renderModules`
- refactors `renderModules` to make its usage and inner workings clearer
- adds tests for `renderModules`
- adds component `BlogPostMetaInformation` for repeated code in blog page, blog post page, search results

### CODE REVIEW

**Comment by daaain** [comment]
Love the attention to details: the cleaner object destructuring, the single quotes, the CSS class names, the video block...

But most importantly this new `renderModules` API is so much cleaner! Yay for functions instead of switch! And tests :heart: !

:shipit:

**Comment by davidey** [comment]
Looks good! :+1:

**Comment by arnau** [comment]
:+1:

**Comment by phil-linnell** [comment]
Everyone is raving about it! :+1: 
Will merge now

**Pull request merged**
