### PR TITLE
Docs/vault

### PR DESCRIPTION
**Pull request by arnau**
@phil-linnell @daaain @ch2ch3 @petronbot please take a look at this PR.  It explains how to create the vault yourself and provides a make task to create the self-signed SSL certificate.

The README should be enough to review the PR.

*IMPORTANT* If you create self-signed certificate you probably want to keep the vault-2015.tar file I shared with you at some point so you can later on use `make vault-load VAULT_PATH=path/to/vault-2015.tar` to put our SSL cert back.

### CODE REVIEW

**Comment by phil-linnell** [comment]
:+1:

**Comment by ch2ch3** [comment]
LGTM

**Comment by daaain** [comment]
Haven't tried the process, but checking the diff it looks good :shipit:

**Comment by adeel-raza** [comment]
Not sure how to setup this, can the docs be more explanatory. ?

**Comment by arnau** [comment]
What are you missing from https://github.com/ustwo/ustwo.com-frontend#credentials--vault ?  A bit more detail on what is unclear would help

**Comment by adeel-raza** [comment]
The Note "If you use self-signed certificates you probably want to use your docker IP (e.g. docker-machine ip dev) instead of a custom ustwo.com domain."

Can this be explained more. ?
Thanks.

**Comment by arnau** [comment]
Sure,

Setting up the `ustwo.com` domain(s) is only useful for the ustwo team.  So this paragraph only says you should skip any step regarding that.

Then, to reach the app you have to know were is your Docker server running (binding ports).  For example, if you use Docker Machine, you will get the ip running `docker-machine ip` (assuming you are using the default environment), so you can use in your browser `https://<ip from docker machine>:9443`.

If you are using, say, Docker for Mac beta, you'll be fine using just `https://localhost:9443` given it binds to localhost by default.  I presume Docker for Windows will behave in a similar fashion but I don't have any instance available to double check.

Does this help a bit?

**Comment by adeel-raza** [comment]
Yes, this helps. Thanks for responding.
Actually, we were having problem with SSL certificate generation step

make vault-generate-cert
make vault-build

It would be very helpful if you add more explanation to docs for this.

**Comment by arnau** [comment]
What kind of problem?

**Comment by diegovilarinho** [comment]
This is my problem to run `make vault-generate-cert`

`Generating RSA private key, 1024 bit long modulus
..................++++++
....................................++++++
e is 65537 (0x10001)
Generating a 4096 bit RSA private key
......++
.......................................................++
writing new private key to '/certs/usweb.key'
-----
No value provided for Subject Attribute C, skipped
No value provided for Subject Attribute ST, skipped
No value provided for Subject Attribute L, skipped
No value provided for Subject Attribute O, skipped
Signature ok
subject=/CN=usweb
Getting Private key
chown: /Applications/MAMP/htdocs/diegovilarinhoo/ustwo/ustwo.com-frontend/etc/nginx/ssl: No such file or directory
make: *** [vault-generate-cert] Error 1`

**Pull request closed without merging**
