### PR TITLE
Features/ansible driver

### PR DESCRIPTION
**Pull request by arnau**
@collingo @daaain This branch evolves the ansible playbooks to provision usweb hosts with the make tasks so we can avoid using docker-machine.

The documentation is inside `tasks/provision.mk`.  Check, test, play.

The **canary** playbook provisions the next production machine.  So it will be irrelevant after the switch.

### CODE REVIEW

**Comment by daaain** [comment]
Wait, so with this config now staging.ustwo.com is the server and not local staging URL?

**Comment by arnau** [comment]
Ah damn, no! the domain is the other one, the new 2015.ustwo.com

**Comment by daaain** [comment]
So that should be usweb-staging.ustwo.com then, unless we can come up with a better one :)

**Comment by arnau** [comment]
Ok, fixed.

**Comment by daaain** [comment]
@arnau so should we get rid of Canary now and merge?

**Comment by arnau** [comment]
Canary can be removed, yes.

**Comment by arnau** [comment]
Removed canary.  I will merge as soon as circle gives an ok

**Pull request merged**
