### PR TITLE
Features/page loader

### LINKED ISSUE #267: Blog post page transition in
We should make sure that the page looks nice even while we are loading data / rendering content

- [ ] UI assets from Ben M / Danson
- [ ] Implement assets

Fixes #302

### PR DESCRIPTION
**Pull request by collingo**
@ustwo/usweb-dev @collingo what do you think?

We won't merge until we have had a design review :)

Fixes #267

### CODE REVIEW

**Comment by phil-linnell** [comment]
It's beautiful! :+1: 
Merge

**Comment by phil-linnell** [comment]
Good to go, approval from VD + manual tests seem good

**Comment by ch2ch3** [comment]
Just discussed with @collingo: we have nested `TransitionManager`s in the `app` component now but only really need the inner one, so at some point it would be nice to do a refactor to get rid of the outer one :)

**Comment by collingo** [comment]
Thanks @ch2ch3, have made that change along with the conversion to React.createClass as you suggested

**Pull request merged**
